feat(packagejson): added option to allow packagejson field
Kamiapp-fr/vite-plugin-cem pull request #4
Opened 2023-02-03 21:54 UTC by ozee

Using the cli-helpers utility from `@custom-elements-manifest/analyzer` I provided an option with a false default to the plugin using the function that adds the `custom-elements` property to the `package.json`.

fixes #3

2023-02-06 09:49 UTC, EmilienLeroy requested changes
Hello @ozee,
Thank you for your contribution to this project. I suggest not using the analyzer function as it automatically adds the custom-elements.json at the end of the path.

```ts
import {
  join,
  relative,
  sep,
  posix,
} from 'path';
```

```ts
   generateBundle(this, { dir }) {
      const path = join(dir, output);
      const manifest = createManifest(files, createManifestOptions);

      mkdirSync(dir, { recursive: true });
      writeFileSync(path, JSON.stringify(manifest));

      if (packageJson) {
        const packageJsonPath = `${process.cwd()}${sep}package.json`;
        const pkg = JSON.parse(readFileSync(packageJsonPath).toString());
        const relativePath = relative(process.cwd(), path);

        pkg.customElements = relativePath.split(sep).join(posix.sep);
        writeFileSync(packageJsonPath, `${JSON.stringify(pkg, null, 2)}\n`);
      }
    },
```

This code utilize a relative path instead of an absolute path from Vite, and will enable the use of a custom name for the manifest.
What is your opinion?

2023-02-06 09:51 UTC, EmilienLeroy commented
@ozee 
I'll let you update your code, but if you prefer, I can do it for you.

2023-02-06 16:04 UTC, ozee commented
Hi @EmilienLeroy I like this idea, but I had not seen an option to set the name of the `custom-elements.json` prior. Is that something that is currently supported?

2023-02-06 17:06 UTC, EmilienLeroy commented
@ozee 
The plugin enables you to modify both the path and the name of the manifest file using the `output` option.

```ts
  /**
   * Define where will be serve the manifest.
   * This option only work in development mode.
   * @default '/custom-elements.json'
   */
  endpoint?: string,
  /**
   * Define where will be build the final manifest.
   * This option only work in production mode.
   * @default 'custom-elements.json'
   */
  output?: string,
```

For example, with this configuration:

```ts
export default defineConfig({
  plugins: [
    VitePluginCustomElementsManifest({
      files: ['./src/my-element.ts'],
      lit: true,
      output: 'test-manifest.json',
    }),
  ],
});
```

It will create a production manifest in the `dist/test-manifest.json` file. To change the name during development, use the `endpoint` option.

2023-02-06 17:09 UTC, ozee commented
ah, that makes complete sense. I am fine with the change as you made it. I can take that and modify the request if you like.

2023-02-06 17:18 UTC, EmilienLeroy commented
If you have time, I let you finish the feature! 😄

2023-02-06 18:30 UTC, ozee commented
I notice that this line, `const packageJsonPath = '${process.cwd()}${sep}package.json}\n';` (backticks not formatting right) always points to the root `package.json` from where the script is run. Is that how we want it to run? I was writing a test for it and noticed it when running against the lit example since we aren't targeting the package.json for the example.

2023-02-07 07:47 UTC, EmilienLeroy commented
I see the problem, but couldn't find the current directory when generating the bundle with Vite. It always gives the `dist` directory. The `npm run lit:build`  use  the  `npm -C example/lit-ts run build` command which resolves the issue by updating the current directory. Let's stick with this for now, but if we find a way to get the current directory during Vite bundle generation, we should implement it.

2023-02-12 02:13 UTC, ozee commented
Work got busy for me during the week, I'll comment out my test so that it doesn't affect the main package.json for now, and maybe in the future it can be uncommented when this is worked out.

2023-02-13 16:12 UTC, merged

2023-02-13 16:19 UTC, ozee commented
@EmilienLeroy fantastic! thank you for working with me on this! I was able to contribute!